### ISSUE TITLE
III/02/BankDemo.java - throws error

### ISSUE THREAD

**Issue by the-code-innovator** [the-code-innovator/javalab#1]
$ javac BankDemo.java
BankDemo.java:1: error: package pkbanking does not exist
import pkbanking.* ;
^
BankDemo.java:5: error: cannot access Customer
    Customer c = new Customer(1001, "Aravind", "none");
    ^
  bad source file: ./Customer.java
    file does not contain class Customer
    Please remove or make sure it appears in the correct subdirectory of
the sourcepath.
2 errors

**Comment by jaikanthjay46** [comment]
Check the latest commit
