### ISSUE TITLE
BankDemo throws error at runtime.

### ISSUE THREAD

**Issue by the-code-innovator** [the-code-innovator/javalab#2]
> Exception in thread "main" java.lang.NullPointerException
> 	at pkbanking.Customer.push(Customer.java:99)
> 	at pkbanking.Customer.createAccount(Customer.java:26)
> 	at BankDemo.main(BankDemo.java:6)
- [push method](https://github.com/the-code-innovator/javalab/blob/master/III/02/Source/Customer.java#L97) :
```java
  private static SBAccount[] push(SBAccount array[], SBAccount pushedItem){
    SBAccount[] longer = new SBAccount[array.length + 1];
    System.arraycopy(array, 0, longer, 0, array.length);
    longer[array.length] = pushedItem;
    return longer;
  }
```
- [createAccount method](https://github.com/the-code-innovator/javalab/blob/master/III/02/Source/Customer.java#L17) : 
```java
  public void createAccount(int type){
    Scanner in = new Scanner(System.in);
    if(type == 1){
      System.out.print("\nEnter Account Number : ");
      int accnumber = in.nextInt();
      System.out.print("\nEnter Opening Balance for the Savings Account : ");
      double balance = in.nextDouble();
      SBAccount temp = new SBAccount(accnumber, balance);                  //devise a method to push the new object into the dynamic array of objects.
      this.savings = push(this.savings, temp);
    }
    if(type == 2){
      System.out.print("\nEnter Account Number : ");
      int accnumber = in.nextInt();
      System.out.print("\nEnter Period : ");
      int period = in.nextInt();
      System.out.print("\nEnter Deposit Amount for the Fixed Deposit Account : ");
      double depositAmount = in.nextDouble();
      FDAccount temp = new FDAccount(accnumber, depositAmount, period);    //devise a method to push the new object into the dynamic array of objects.
      this.deposits = push(this.deposits, temp);
    }
    else{
      System.out.print("\nERROR 00CE-001: Unable to create Account, type must be either Savings or Fixed Deposit !");
    }
  }
```
- [main method](https://github.com/the-code-innovator/javalab/blob/master/III/02/BankDemo.java#L4) : 
```java
  public static void main(String[] args){
    Customer c = new Customer(1001, "Aravind", "none");
    c.createAccount(1);
    c.createAccount(2);
    c.transaction(1);
    c.transaction(2);
  }
```

@jaikanthjay46  look into this.

**Comment by jaikanthjay46** [comment]
Done. :-)

**Comment by the-code-innovator** [comment]
**

- Why is this causing an error if the packages are nested under a super package? 

- This is what is asked in the exercise :

** 
> Create a package named pkbanking. In that package define a sub package named pkinterface. The package pkinterface contains an interface named Transaction with a data member min_balance initialized to 500, two methods namely void withdraw(double) and void deposit(double) and another interface named InterestRate with two data members sbrate with 4%, fdrate with 8.25%.
> Create another package named pkaccount. In that package create an abstract class called Account that has the protected data members accnumber of int type, balance of double, constructors for initialization. Define two subpackages sb and fd in pkaccount. In sb package derive a class called SBAccount from Account class that implements both Transaction and InterestRate interfaces. Also it has constructors for initialization using super class constructors, deposit(double), withdraw(double), and calc_interest() methods. Provide a parameterized constructor with two parameters account number, and init_balance and assign these values to the appropriate
> data members of the class using super class constructor. The deposit method should take one double type argument amount and adds the amount to the balance if the amount is positive. The withdraw method, should take one double type argument amount and checks if balance - amount is greater than min_balance. If so, it should subtract the amount from balance. Otherwise it should display error message. The calc_interest() method should compute interest for the balance amount available @ sbrate p.a. and the interest amount should be credited to the balance.
> In fd package derive a class called FDAccount from Account class that implements InterestRate interface. It has one data member period of int type. Provide parameterized constructor with parameters for accno, period and deposit amount for initializing them using super class constructor. Provide a method called calc_interest() for calculating interest for the deposit amount for the given period @ fdrate p.a. and returns the calculated interest, and another method called close() which calls calc_interest() add it to the balance.
> Create third package named pkcustomer which contains a class Customer. The data members of the class are cust_id of int type, name, and address of string type, and Array of objects of SBAccount and FDAccount. Provide parameterized constructor with cust_id, name and address as parameters for initializing. Provide a method called createAccount(int type). Based on the value of type (SB, or FD) create a new account of given type and store it in the corresponding array. Provide a method transaction(int type) {type may be withdraw, deposit or calc_interest on SBAccount, closing of FDAccount} to perform the requested transaction on the requested account object.
> To demonstrate all the functionalities of above classes, create a class called BankDemo and declare a main method to create an array of 5 elements of Customer objects, and perform manipulations on the objects by creating SB and FD accounts, depositing and withdrawing amount from SB accounts, and closing FD accounts.
